### ISSUE TITLE
multiple rss feeds

### ISSUE THREAD

**Issue by temporhodes** [viperadnan-git/rss-feed-telegram-bot#1]
Hello.
Please add support for multiple rss feeds.

thanks.

**Comment by viperadnan-git** [comment]
You can add it yourself if you know little bit of python.

Hint - Make another function called `check_feed2` for second feed. And add a scheduler for it.

**Comment by temporhodes** [comment]
Thanks.
it worked.

**Comment by viperadnan-git** [comment]
Fixed in newest version <https://github.com/viperadnan-git/rss-feed-telegram-bot/commit/9ac878e574ba6eb6194f26f733bde32d9cb84804>
