### ISSUE TITLE
multi feed

### ISSUE THREAD

**Issue by ghost** [viperadnan-git/rss-feed-telegram-bot#2]
can I use multi feed rss

**Comment by viperadnan-git** [comment]
Yes, modify it.

**Comment by ghost** [comment]
how?

**Comment by viperadnan-git** [comment]
See issue #1

**Comment by ghost** [comment]
can you teach me?I make check feed2 but nothing happens

**Comment by ghost** [comment]
[check this](https://urlbox.paduhq.com/862693092746668/rss.py)

**Comment by viperadnan-git** [comment]
Fixed in newest version <https://github.com/viperadnan-git/rss-feed-telegram-bot/commit/9ac878e574ba6eb6194f26f733bde32d9cb84804>
