### ISSUE TITLE
Need little help regarding Database URL

### ISSUE THREAD

**Issue by Ajayveer9911github** [viperadnan-git/rss-feed-telegram-bot#9]
Where to add DATABASE_URL?  In Config.env.template, there isn't  DATABASE_URL field. 
Where should I add my DATABASE_URL?

**Comment by xgorn** [comment]
https://github.com/viperadnan-git/rss-feed-telegram-bot/blob/9ac878e574ba6eb6194f26f733bde32d9cb84804/sql/__init__.py#L6
